#!/bin/bash
cd  ..

# Compile the project without changes
MYPYPATH=./DistractionFreeHints/typings mypy  DistractionFreeHints/DistractionFreeHints.py

# Watch for changes and compile the project each time
MYPYPATH=./DistractionFreeHints/typings chokidar "./DistractionFreeHints/**/*.py" -c "mypy  DistractionFreeHints/DistractionFreeHints.py"
